### ISSUE TITLE
store/pre-auth-hook: error if no session token sent

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server#524]
If a request has no session token, then we do `return reply(Boom.unauthorized())`, but that only calls the next `.then` callback and sets `session` in it to `Boom.unauthorized()`.

We have to throw an error instead and set `error.status` to 404 so that the `.catch` callback can take care of it

**Comment by gr2m** [comment]
I _think_ this is resolved as part of #526, see the comment at https://github.com/hoodiehq/hoodie-server/pull/526/files#diff-0c9cbe67579a94330b4f853044a4717dR43. Can you confirm that?

**Comment by benwhite-deltas** [comment]
Yes, this is indeed now resolved, though the test suite is still throwing out a warning as a result of jupiter/simple-mock#22. I'll update the above PR to fix this only.
